name: Test Hurl PostgreSQL

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]
    timeout-minutes: 10
    steps:
    - name: Start PostgreSQL
      run: |
        sudo systemctl start postgresql.service
        pg_isready
        sudo -u postgres createdb db
        printf "0000\n0000" | sudo -u postgres createuser -s -d -r -P runner
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set up uv
      uses: astral-sh/setup-uv@v5
    - name: Install Hurl
      run: |
        curl -sSL https://github.com/Orange-OpenSource/hurl/releases/latest/download/hurl-7.1.0-x86_64-unknown-linux-gnu.tar.gz | tar xz
        echo "$PWD/hurl-7.1.0-x86_64-unknown-linux-gnu/bin" >> "$GITHUB_PATH"
    - name: Install Dependencies
      run: make sync
    - name: Migrate
      run: |
        DATABASE_URL=postgresql://runner:0000@localhost:5432/db uv run python manage.py migrate
    - name: Run Django
      run: |
        make run DATABASE_URL=postgresql://runner:0000@localhost:5432/db ALLOWED_HOSTS=* &
        sleep 4
    - name: Run Tests
      run: make test-hurl
